# Generated by Django 4.0.5 on 2022-06-02 05:58

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('type_of_treatment', models.CharField(default='Callback', max_length=10)),
                ('called_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HelpQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Q&A',
                'verbose_name_plural': 'Help Q&A',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Advantage',
                'verbose_name_plural': 'Our Advantages',
            },
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'PHONE'), ('WHATSAPP', 'WHATSAPP'), ('INSTAGRAM', 'INSTAGRAM'), ('TELEGRAM', 'TELEGRAM'), ('EMAIL', 'EMAIL')], help_text='Choose from list', max_length=100)),
                ('link_to', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeaderObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, upload_to='images/')),
                ('footer_logo', models.ImageField(blank=True, upload_to='images/')),
                ('text_info', models.TextField(blank=True)),
                ('header_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('social_type', models.ManyToManyField(to='information.socialtypes')),
            ],
        ),
    ]
