# Generated by Django 4.0.5 on 2022-06-03 11:49

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=255, unique=True)),
                ('actual_price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('size_line', models.CharField(max_length=100)),
                ('tissue_composition', models.CharField(max_length=250)),
                ('quantity_in_line', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=100)),
                ('bestseller', models.BooleanField(default=False)),
                ('novelty', models.BooleanField(default=True)),
                ('favorite', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='products.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='31639c', image_field=None, max_length=18, samples=None)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_objects', to='products.product')),
            ],
        ),
    ]
