# Generated by Django 4.0.5 on 2022-06-03 11:53

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstyles',
            name='color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
