# Generated by Django 4.0.5 on 2022-06-03 10:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productstyles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstyles',
            name='color',
            field=colorfield.fields.ColorField(default='31639c', image_field=None, max_length=18, samples=None),
        ),
    ]
