# Generated by Django 3.2.12 on 2022-06-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productstyles_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstyles',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_styles', to='products.product'),
        ),
    ]
