# Generated by Django 3.2.12 on 2022-06-13 05:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productstyles_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productstyles',
            options={'verbose_name': 'Отдельный товар', 'verbose_name_plural': 'Товары по отдельности'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(help_text='Актуальная цена на данный момент.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Скидка в процентах.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Цена до скидки, создаётся атвтоматически после указания скидки.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_line',
            field=models.PositiveIntegerField(blank=True, help_text='Количество в линейке, создаётся атвтоматически после линейки размеров.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_line',
            field=models.CharField(max_length=5, validators=[products.models.size_line_validator]),
        ),
    ]
