# Generated by Django 3.2.12 on 2022-06-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220613_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstyles',
            options={'verbose_name': 'Товары по отдельности', 'verbose_name_plural': 'Товары по отдельности'},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstyles')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
