# Generated by Django 3.2.12 on 2022-06-28 05:22

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220615_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_line',
            field=models.PositiveIntegerField(blank=True, help_text='Количество в этой  линейке  создаётся атвтоматически после линейки размеров.'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created=True, choices=[('НОВЫЙ', 'НОВЫЙ'), ('ОФОРМЛЕН', 'ОФОРМЛЕН'), ('ОТМЕНЕН', 'ОТМЕНЕН')], default='НОВЫЙ', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('public_agreement', models.BooleanField(default=False)),
                ('lines_amount', models.PositiveIntegerField(default=0)),
                ('products_amount', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('actual_price', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('ordered_products', models.ManyToManyField(to='products.Cart')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
